version: 2.1

build:
  docker:
    - image: mimatila/rails-example-project
  working_directory: ~/
  steps:
    - checkout
    - attach_workspace:
        at: ~/
    - run:
        name: Build
        #command: npm run build
    - persist_to_workspace:
        root: .
        paths:
          - .next
          
  workflows:
  version: 2

  test-build-deploy:
    jobs:
      - image: mimatila/rails-example-project
      - lint:
          requires:
            - build
          
deploy-dev:
      machine: true
      steps:
        - checkout
        - run:
            name: Build and push Docker image to Heroku
            command: |
              sudo curl https://cli-assets.heroku.com/install.sh | sh
              HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
              HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a python-django-starter web
              HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a python-django-starter web
