version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10 # Invoke the Heroku orb

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter
jobs:
  build:
    docker:
      - image: mimatila/rails-example-project
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: |-
    cd /usr/local/share
    sudo wget https://repo1.maven.org/maven2/com/github/klieber/phantomjs/1.9.0/phantomjs-1.9.0-linux-x86_64.tar.bz2
    sudo tar xjf phantomjs-1.9.0-linux-x86_64.tar.bz2
    sudo ln -s /usr/local/share/phantomjs-1.9.0-linux-x86_64/bin/phantomjs /usr/local/share/phantomjs
    sudo rm /usr/local/bin/phantomjs
    sudo ln -s /usr/local/share/phantomjs-1.9.0-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs
    sudo ln -s /usr/local/share/phantomjs-1.9.0-linux-x86_64/bin/phantomjs /usr/bin/phantomjs
      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      - run:
          name: Run tests
          command: rake
