version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10 # Invoke the Heroku orb

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter
jobs:
  build:
    docker:
      - image: mimatila/rails-example-project
    working_directory: ~/
    steps:
      - checkout
      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      # Database setup
      #- run: bundle exec rake db:create db:schema:load
      #- run:
      #    name: Run tests
      #    command: rake

          
deploy-dev:
      machine: true
      steps:
        - checkout
        - run:
            name: Build and push Docker image to Heroku
            command: |
              sudo curl https://cli-assets.heroku.com/install.sh | sh
              HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
              HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a python-django-starter web
              HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a python-django-starter web
