version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10 # Invoke the Heroku orb

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter
jobs:
  build:
    docker:
      - image: mimatila/rails-example-project
    working_directory: ~/home/mimatila/Docker/rails-example-project/rails-example-project-master
    steps:
        - checkout
        - run:
            name: Build and push Docker image to Heroku
            command: |
              curl https://cli-assets.heroku.com/install.sh | sh
              HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
              HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a appmika2 web
              HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a appmika2 web
